version: '2.1'

volumes:
  mongo_data:

services:
  kong-database:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure

  konga:
    image: pantsel/konga:next #(or latest)
    container_name: konga
    depends_on:
      - kong
    ports:
      - 1337:1337
    links:
      - mongo:db
      - kong:kong
    environment:
      - DB_ADAPTER=mongo
      - DB_HOST=mongo
      - DB_DATABASE=konga
      - NODE_ENV=development

  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 127.0.0.1:27017:27017

  kong:
    image: kong:latest
    command: kong start --run-migrations
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001        
    ports:
      - "80:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
      - "7946:7946"
    restart: on-failure